import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { Amplify } from 'aws-amplify';
import { signIn, signOut, signUp, confirmSignUp, fetchAuthSession, getCurrentUser } from '@aws-amplify/auth';
import { QRCodeSVG } from 'qrcode.react';
import './styles.css';
type Config={region:string;apiUrl:string;userPoolId:string;userPoolClientId:string}; type Me={name:string;email:string;role:'STUDENT'|'TEACHER';userId:string};
let config:Config;
export function setRuntimeConfig(value: Config){config=value;}
export function friendlyError(code?:string){return ({QR_EXPIRED:'This QR code has expired. Please scan the current code displayed by your instructor.',ATTENDANCE_ALREADY_RECORDED:'Your attendance for this class has already been recorded.',NOT_ENROLLED:'You are not enrolled in this course.',SESSION_CLOSED:'This attendance session has closed.'} as Record<string,string>)[code??'']??'We could not contact the server. Check your connection and try again.';}
export async function api(path:string, init?:RequestInit){try{const session=await fetchAuthSession();const res=await fetch(`${config.apiUrl}${path}`,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${session.tokens?.idToken?.toString()??''}`,...init?.headers}});const data=await res.json();if(!res.ok)throw new Error(data.error?.message??friendlyError(data.error?.code));return data;}catch(error){if(error instanceof Error && error.message!=='Failed to fetch')throw error;throw new Error(friendlyError());}}
export function Shell({children}:{children:React.ReactNode}){const nav=useNavigate();const location=useLocation();const [me,setMe]=useState<Me>();useEffect(()=>{api('/me').then(setMe).catch(()=>nav(`/login?returnTo=${encodeURIComponent(location.pathname+location.search)}`));},[nav,location.pathname,location.search]);return <main><header><Link to="/">CloudAttend</Link><span>{me?.name}</span><button onClick={()=>signOut().then(()=>nav('/login'))}>Sign out</button></header><section>{children}</section></main>}
export function Login(){const nav=useNavigate();const [params]=useSearchParams();const [error,setError]=useState('');async function submit(f:FormData){try{await signIn({username:String(f.get('email')),password:String(f.get('password'))});nav(params.get('returnTo')||'/');}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.');}}return <Auth title="Welcome back"><form action={submit}><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label>{error&&<p role="alert">{error}</p>}<button>Sign in</button></form><Link to="/register">Student registration</Link></Auth>}
export function Register(){const [step,setStep]=useState<'register'|'confirm'>('register');const [email,setEmail]=useState('');const [error,setError]=useState('');async function submit(f:FormData){try{const password=String(f.get('password'));if(password!==String(f.get('confirmPassword'))){setError('Passwords do not match.');return;}const e=String(f.get('email'));await signUp({username:e,password,options:{userAttributes:{email:e,name:String(f.get('name')),'custom:rollNo':String(f.get('rollNo'))}}});setEmail(e);setStep('confirm');}catch(x){setError(x instanceof Error?x.message:'Registration failed.');}}return <Auth title="Create student account">{step==='register'?<form action={submit}><label>Full name<input name="name" required/></label><label>Roll number<input name="rollNo" required/></label><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={12} required/></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} required/></label>{error&&<p role="alert">{error}</p>}<button>Create account</button></form>:<form action={async f=>{await confirmSignUp({username:email,confirmationCode:String(f.get('code'))});location.href='/login';}}><p>Enter the verification code sent to {email}.</p><label>Verification code<input name="code" required/></label><button>Verify account</button></form>}</Auth>}
function Auth({title,children}:{title:string;children:React.ReactNode}){return <main className="auth"><h1>{title}</h1>{children}</main>}
function Dashboard(){const courses=useQuery({queryKey:['courses'],queryFn:()=>api('/courses')}); return <Shell><h1>Dashboard</h1><p>Manage attendance securely with rotating QR codes.</p>{courses.isLoading ? <p>Loading courses…</p> : <div className="grid">{courses.data?.length ? courses.data.map((c:any) => <article key={c.courseId}><h2>{c.courseName}</h2><p>{c.courseCode} · {c.semester} · Section {c.section}</p><Link to={`/courses/${c.courseId}`}>Open course</Link></article>) : <p>No courses yet.</p>}</div>}</Shell>}
function Course(){const {ignored:id}=useParams();const nav=useNavigate();const [session,setSession]=useState<any>();const [qr,setQr]=useState<any>();async function start(){const created=await api(`/courses/${id}/sessions`,{method:'POST',body:JSON.stringify({durationMinutes:10})});setSession(created);const q=await api(`/sessions/${created.sessionId}/qr-token`);setQr(q);}return <Shell><h1>Course</h1><button onClick={start}>Start attendance</button>{session&&<article><h2>Attendance open</h2><p>QR refreshes automatically. Remaining until {new Date(session.scheduledEndTime).toLocaleTimeString()}.</p>{qr&&<QRCodeSVG value={`${location.origin}/check-in?token=${encodeURIComponent(qr.token)}`} size={260}/>}<button onClick={async()=>{await api(`/sessions/${session.sessionId}/close`,{method:'POST'});nav('/');}}>Close attendance</button></article>}</Shell>}
export function CheckIn(){const [params]=useSearchParams();const [message,setMessage]=useState('');useEffect(()=>{const token=params.get('token');if(token)api('/attendance/check-in',{method:'POST',body:JSON.stringify({token})}).then(()=>{history.replaceState({},'',location.pathname);setMessage('Attendance Recorded');}).catch(e=>setMessage(e instanceof Error?e.message:friendlyError()));},[params]);return <Shell><h1>{message||'Recording attendance…'}</h1><p>Use the current QR code displayed by your instructor.</p></Shell>}
export function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/check-in" element={<CheckIn/>}/><Route path="/courses/:ignored" element={<Course/>}/><Route path="/" element={<Dashboard/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
async function boot(){config=await fetch('/config.json',{cache:'no-store'}).then(r=>r.json());Amplify.configure({Auth:{Cognito:{userPoolId:config.userPoolId,userPoolClientId:config.userPoolClientId}}});try{await getCurrentUser();}catch{ /* route components handle signed-out navigation */ }createRoot(document.getElementById('root')!).render(<StrictMode><QueryClientProvider client={new QueryClient()}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></StrictMode>)}if(document.getElementById('root'))void boot();
