import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import type { APIGatewayProxyEventV2, APIGatewayProxyResultV2 } from 'aws-lambda';
import { CheckInSchema, CreateCourseSchema, EnrollStudentSchema, QR_TOKEN_LIFETIME_SECONDS, StartSessionSchema, UpdateCourseSchema } from '@cloudattend/shared';

export type RecordItem = Record<string, unknown>;
export interface Store { get(table: string, key: RecordItem): Promise<RecordItem | undefined>; put(table: string, item: RecordItem, condition?: 'absent'): Promise<void>; update(table: string, key: RecordItem, values: RecordItem): Promise<RecordItem>; query(table: string, index: string | undefined, key: string, value: string): Promise<RecordItem[]>; }
export type Config = { users: string; courses: string; enrollments: string; sessions: string; attendance: string; qrSecret: string; reportsBucket?: string };
export class ApiError extends Error { constructor(public status: number, public code: string, message: string) { super(message); } }
const now = () => new Date().toISOString();
const json = (statusCode: number, body: unknown): APIGatewayProxyResultV2 => ({ statusCode, headers: { 'content-type': 'application/json', 'cache-control': 'no-store' }, body: JSON.stringify(body) });
const claims = (e: APIGatewayProxyEventV2) => (e.requestContext as APIGatewayProxyEventV2['requestContext'] & { authorizer?: { jwt?: { claims?: Record<string, string> } } }).authorizer?.jwt?.claims ?? {};
export const identity = (e: APIGatewayProxyEventV2) => ({ id: String(claims(e).sub ?? ''), groups: String(claims(e)['cognito:groups'] ?? '').split(',') });
export function requireRole(e: APIGatewayProxyEventV2, role: 'STUDENT' | 'TEACHER') { const user = identity(e); if (!user.id) throw new ApiError(401, 'UNAUTHENTICATED', 'Sign in is required.'); if (!user.groups.includes(role)) throw new ApiError(403, 'FORBIDDEN', 'You are not authorized for this action.'); return user; }
export const signQr = (payload: Record<string, unknown>, secret: string) => { const data = Buffer.from(JSON.stringify(payload)).toString('base64url'); return `${data}.${createHmac('sha256', secret).update(data).digest('base64url')}`; };
export const verifyQr = (token: string, secret: string) => { const [data, signature] = token.split('.'); if (!data || !signature) throw new ApiError(400, 'INVALID_QR', 'This QR code is invalid.'); const wanted = createHmac('sha256', secret).update(data).digest('base64url'); if (signature.length !== wanted.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(wanted))) throw new ApiError(400, 'INVALID_QR', 'This QR code is invalid.'); let payload: { sessionId: string; courseId: string; exp: number }; try { payload = JSON.parse(Buffer.from(data, 'base64url').toString()); } catch { throw new ApiError(400, 'INVALID_QR', 'This QR code is invalid.'); } if (!payload.sessionId || !payload.courseId || payload.exp * 1000 < Date.now()) throw new ApiError(400, 'QR_EXPIRED', 'This QR code has expired. Please scan the current code displayed by your instructor.'); return payload; };
export async function route(e: APIGatewayProxyEventV2, store: Store, cfg: Config): Promise<APIGatewayProxyResultV2> {
 try { const method = e.requestContext.http.method; const path = e.rawPath; const body = e.body ? JSON.parse(e.body) : {}; const id = identity(e).id;
  if (method === 'GET' && path === '/health') return json(200, { status: 'ok' });
  if (method === 'GET' && path === '/me') { requireRole(e, identity(e).groups.includes('TEACHER') ? 'TEACHER' : 'STUDENT'); const user = await store.get(cfg.users, { userId: id }); return json(200, user); }
  if (method === 'POST' && path === '/courses') { const u = requireRole(e, 'TEACHER'); const input = CreateCourseSchema.parse(body); const course = { ...input, courseId: randomUUID(), teacherId: u.id, createdAt: now(), updatedAt: now() }; await store.put(cfg.courses, course); return json(201, course); }
  if (method === 'GET' && path === '/courses') { const u = requireRole(e, identity(e).groups.includes('TEACHER') ? 'TEACHER' : 'STUDENT'); const courses = u.groups.includes('TEACHER') ? await store.query(cfg.courses, 'teacherId-index', 'teacherId', u.id) : await store.query(cfg.enrollments, 'studentId-index', 'studentId', u.id); return json(200, courses); }
  const courseMatch = path.match(/^\/courses\/([^/]+)$/); if (courseMatch && method === 'PUT') { const u = requireRole(e, 'TEACHER'); await ownedCourse(store, cfg, courseMatch[1], u.id); const updated = await store.update(cfg.courses, { courseId: courseMatch[1] }, { ...UpdateCourseSchema.parse(body), updatedAt: now() }); return json(200, updated); }
  const roster = path.match(/^\/courses\/([^/]+)\/students$/); if (roster) { const u = requireRole(e, 'TEACHER'); await ownedCourse(store, cfg, roster[1], u.id); if (method === 'POST') { const { studentId } = EnrollStudentSchema.parse(body); const student = await store.get(cfg.users, { userId: studentId }); if (!student || student.role !== 'STUDENT') throw new ApiError(404, 'STUDENT_NOT_FOUND', 'Student was not found.'); const item = { courseId: roster[1], studentId, enrolledAt: now() }; await store.put(cfg.enrollments, item, 'absent'); return json(201, item); } if (method === 'GET') return json(200, await store.query(cfg.enrollments, undefined, 'courseId', roster[1])); }
  const enrollRemove = path.match(/^\/courses\/([^/]+)\/students\/([^/]+)$/); if (enrollRemove && method === 'DELETE') throw new ApiError(501, 'NOT_IMPLEMENTED', 'Enrollment removal is not available in this deployment.');
  const sessionStart = path.match(/^\/courses\/([^/]+)\/sessions$/); if (sessionStart && method === 'POST') { const u = requireRole(e, 'TEACHER'); await ownedCourse(store, cfg, sessionStart[1], u.id); const input = StartSessionSchema.parse(body); const start = Date.now(); const session = { sessionId: randomUUID(), courseId: sessionStart[1], teacherId: u.id, startTime: new Date(start).toISOString(), scheduledEndTime: new Date(start + input.durationMinutes * 60000).toISOString(), status: 'OPEN', tokenLifetimeSeconds: QR_TOKEN_LIFETIME_SECONDS, createdAt: now() }; await store.put(cfg.sessions, session); return json(201, session); }
  const qr = path.match(/^\/sessions\/([^/]+)\/qr-token$/); if (qr && method === 'GET') { const u = requireRole(e, 'TEACHER'); const session = await getSession(store, cfg, qr[1]); if (session.teacherId !== u.id) throw new ApiError(403, 'FORBIDDEN', 'You do not own this session.'); assertOpen(session); const issuedAt = Math.floor(Date.now()/1000), expiresAt = issuedAt + QR_TOKEN_LIFETIME_SECONDS; return json(200, { token: signQr({ sessionId: session.sessionId, courseId: session.courseId, iat: issuedAt, exp: expiresAt, jti: randomUUID() }, cfg.qrSecret), issuedAt, expiresAt }); }
  const close = path.match(/^\/sessions\/([^/]+)\/close$/); if (close && method === 'POST') { const u = requireRole(e, 'TEACHER'); const session = await getSession(store, cfg, close[1]); if (session.teacherId !== u.id) throw new ApiError(403, 'FORBIDDEN', 'You do not own this session.'); return json(200, await store.update(cfg.sessions, { sessionId: close[1] }, { status: 'CLOSED', actualEndTime: now() })); }
  if (method === 'POST' && path === '/attendance/check-in') { const u = requireRole(e, 'STUDENT'); const qrPayload = verifyQr(CheckInSchema.parse(body).token, cfg.qrSecret); const session = await getSession(store, cfg, qrPayload.sessionId); assertOpen(session); if (session.courseId !== qrPayload.courseId || Date.parse(session.scheduledEndTime) < Date.now()) throw new ApiError(400, 'SESSION_CLOSED', 'This attendance session has closed.'); const enrollment = await store.get(cfg.enrollments, { courseId: session.courseId, studentId: u.id }); if (!enrollment) throw new ApiError(403, 'NOT_ENROLLED', 'You are not enrolled in this course.'); const attendance = { sessionId: session.sessionId, studentId: u.id, courseId: session.courseId, teacherId: session.teacherId, checkInTime: now(), status: 'PRESENT', createdAt: now() }; await store.put(cfg.attendance, attendance, 'absent'); return json(201, attendance); }
  return json(404, { error: { code: 'NOT_FOUND', message: 'Route not found.' } });
 } catch (error) { if (error instanceof ApiError) return json(error.status, { error: { code: error.code, message: error.message } }); if (error && typeof error === 'object' && 'issues' in error) return json(422, { error: { code: 'VALIDATION_ERROR', message: 'Invalid request.' } }); if ((error as Error).name === 'ConditionalCheckFailedException') return json(409, { error: { code: 'ALREADY_EXISTS', message: 'Attendance already recorded.' } }); console.error(JSON.stringify({ operation: 'route', requestId: e.requestContext.requestId, error: (error as Error).message })); return json(500, { error: { code: 'INTERNAL_ERROR', message: 'An unexpected error occurred.' } }); }
}
async function ownedCourse(store: Store, cfg: Config, courseId: string, teacherId: string) { const c = await store.get(cfg.courses, { courseId }); if (!c) throw new ApiError(404, 'COURSE_NOT_FOUND', 'Course was not found.'); if (c.teacherId !== teacherId) throw new ApiError(403, 'FORBIDDEN', 'You do not own this course.'); return c; }
async function getSession(store: Store, cfg: Config, sessionId: string) { const s = await store.get(cfg.sessions, { sessionId }); if (!s) throw new ApiError(404, 'SESSION_NOT_FOUND', 'Session was not found.'); return s as Record<string, any>; }
function assertOpen(s: Record<string, any>) { if (s.status !== 'OPEN') throw new ApiError(400, 'SESSION_CLOSED', 'This attendance session has closed.'); }
